server:
  port : 12190
spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
#    url: jdbc:sqlite:./db/dev.db
    url: jdbc:sqlite:./memo.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB